trigger:
- main

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    efdssdfsfcho Add other tasks to build, test, and deploy your project.
    sdfsdfecho See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
