trigger:
- main

schedules:
- cron: "* */5 * * *"
  displayName: "Every 5 mins"
  branches:
    include:
    - main

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
